# Generated by Django 4.2.5 on 2023-09-24 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='collaborators',
            field=models.ManyToManyField(related_name='books_collaborated', through='main.Collaboration', to=settings.AUTH_USER_MODEL),
        ),
    ]
