# Generated by Django 4.2.5 on 2023-09-24 11:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_book_collaborators'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='owner',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='collaboration',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='collaboration',
            unique_together={('user', 'book')},
        ),
    ]
